### Get all Assignments
GET http://localhost:8080/api/1/assignments

### Get all Assignments by company Id
GET http://localhost:8080/api/1/assignments/company/1

### Get Assignment by id
GET http://localhost:8080/api/1/assignments/1

### Get Assignments by shift id
GET http://localhost:8080/api/1/assignments/shift/1

### Get Assignments by employee id
GET http://localhost:8080/api/1/assignments/employee/1

### Get Assignments by employee id between two Dates
GET http://localhost:8080/api/1/assignments/employee/1/2025-03-24/2025-03-27
