### Get all Assignments
GET http://localhost:8080/api/assignments

### Get Assignment by id
GET http://localhost:8080/api/assignments/1

### Get Assignments by shift id
GET http://localhost:8080/api/assignments/shift/1