### Send Assignment confirmation E-Mail
PUT http://localhost:8080/api/mail/1

### Confirm Assignment (in E-Mail)
PUT http://localhost:8080/api/mail/confirm/1

### Decline Assignment (in E-Mail)
PUT http://localhost:8080/api/mail/decline/1