### Get all Reservations
GET http://localhost:8080/api/1/reservations

### Get all Reservations by Company Id
GET http://localhost:8080/api/1/reservations/company/1

### Get Reservation by Id
GET http://localhost:8080/api/1/reservations/1

### Add a New Reservation
POST http://localhost:8080/api/1/reservations
Content-Type: application/json

{
  "name": "Reservierung Baar",
  "infos": "Erich Baar kommt mit seiner ganzen Familie zum Mittagessen",
  "numberOfPeople": 12,
  "startTime": "11:30:00",
  "endTime": "13:00:00",
  "shiftId": 3
}

### Delete Reservation
POST http://localhost:8080/api/1/reservations/delete/1