### Get all Shifts
GET http://localhost:8080/api/1/shifts
Authorization: Bearer {{access_token}}

### Get Shift by id
GET http://localhost:8080/api/1/shifts/1

### Get Shifts by company id
GET http://localhost:8080/api/1/shifts/company/1

### Get Shifts by date
GET http://localhost:8080/api/1/shifts/date/2025-03-25

### Get Shifts between two dates
GET http://localhost:8080/api/1/shifts/betweendates/2025-03-25/2025-03-27

### Add a New Shift
POST http://localhost:8080/api/1/shifts
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "shiftName": "Test Shift",
  "startTime": "2024-12-19T09:00:00",
  "endTime": "2024-12-19T17:00:00",
  "companyId": 1
}

### Delete Shift
DELETE http://localhost:8080/api/1/shifts/delete/3
Authorization: Bearer {{access_token}}

### Create Shift with Assignments
POST http://localhost:8080/api/1/shifts/create_with_assignments
Content-Type: application/json

{
  "shiftCreateDTO": {
    "startTime": "2024-12-19T09:00:00",
    "endTime": "2024-12-19T17:00:00",
    "companyId": 1
  },
  "assignmentCreateDTOs": [
    {
      "employee": 1,
      "role": 1
    },
    {
      "employee": 2,
      "role": 2
    }
  ]
}