### Get all Shift Templates
GET http://localhost:8080/api/1/shift-templates

### Create a new Shift Template
POST http://localhost:8080/api/1/shift-templates
Content-Type: application/json

{
  "shiftTemplateName": "Hochzeit",
  "companyId": 1,
  "templateRoles": [
    {
      "roleId": 1,
      "count": 2
    },
    {
      "roleId": 3,
      "count": 1
    }
  ]
}