version: "3.9"
services:
  backend:
    build:
      context: ../backend/instaff-server
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: ./web
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
