version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: instaff-db
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5423:5432"  # host:container
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: pfarrhoferphilip/instaff-server
    container_name: instaff-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/demo
      QUARKUS_DATASOURCE_USERNAME: demo
      QUARKUS_DATASOURCE_PASSWORD: demo
    ports:
      - "8080:8080"
    networks:
      - backend

  frontend:
    image: pfarrhoferphilip/instaff-frontend
    container_name: instaff-frontend
    ports:
      - "4200:80"  # Host port 4200 maps to nginx's port 80
    networks:
      - backend

networks:
  backend:
